### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by sudoskys** [Blarc/ai-commits-intellij-plugin#123]
```
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
    at com.intellij.idea.Main.mainImpl(Main.kt:63)
    at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
    at com.intellij.idea.Main.main(Main.kt:46)
    Suppressed: com.intellij.diagnostic.PluginException: com.github.blarc.ai.commits.intellij.plugin.settings.AppSettings [Plugin: com.github.blarc.ai-commits-intellij-plugin]
        at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2(ComponentManagerImpl.kt:854)
        at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:806)
        at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:403)
        at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:58)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invokeSuspend(ApplicationLoader.kt:197)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invoke(ApplicationLoader.kt)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invoke(ApplicationLoader.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
        at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader.initServiceContainer(ApplicationLoader.kt:196)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader.access$initServiceContainer(ApplicationLoader.kt:1)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$1.invokeSuspend(ApplicationLoader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    Caused by: com.intellij.platform.instanceContainer.internal.InstanceAlreadyRegisteredException: com.github.blarc.ai.commits.intellij.plugin.settings.AppSettings
        at com.intellij.platform.instanceContainer.internal.InstanceRegistrarImpl.registerInitializer(InstanceRegistrarImpl.kt:32)
        at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2Inner(ComponentManagerImpl.kt:910)
        at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2(ComponentManagerImpl.kt:847)
        ... 23 more

```

Pycharm 2023.3 - Ai Commits 1.5.0

**Comment by sudoskys** [comment]
Solved, something fork conflict.
