### ISSUE TITLE
dev.ai4j.openai4j.OpenAiHttpException

### ISSUE THREAD

**Issue by issakk** [Blarc/ai-commits-intellij-plugin#232]
i can get correct respond when i am using other api tools like this
```json
{
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {
                "content": "Hello! How can I assist you today?",
                "role": "assistant"
            }
        }
    ],
    "created": 1724903763,
    "id": "20240829115603a79545029b044bab",
    "model": "glm-4-flash",
    "request_id": "20240829115603a79545029b044bab",
    "usage": {
        "completion_tokens": 11,
        "prompt_tokens": 14,
        "total_tokens": 25
    }
}
```
but when i use this plugin, it shows dev.ai4j.openai4j.OpenAiHttpException 
how can i fix it?

**Comment by Blarc** [comment]
Hey @issakk,
when does this exception occur? Can you maybe post the whole stack trace?

**Comment by issakk** [comment]
thanks for reply @Blarc 
it occurs when  press the Verify button on editting client dialog  and generate commit info
![image](https://github.com/user-attachments/assets/4e258611-d4ee-45d0-99a6-7f7240bfd5c4)
how can i get the whole stack trace?

**Comment by issakk** [comment]
i got the stack trace, how can i fix it?
```
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-15" java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: 
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:177)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:125)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at com.github.blarc.ai.commits.intellij.plugin.settings.clients.LLMClientService$sendRequest$response$1.invokeSuspend(LLMClientService.kt:60)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ApplicationImpl@1275163861), CoroutineName(com.github.blarc.ai.commits.intellij.plugin.settings.clients.openAi.OpenAiClientService), StandaloneCoroutine{Cancelling}@746cb89a, Dispatchers.Default]
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - Caused by: dev.ai4j.openai4j.OpenAiHttpException: 
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
2024-08-30 10:27:03,532 [ 285934]   INFO - STDERR - 	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:177)
2024-08-30 10:27:03,533 [ 285935]   INFO - STDERR - 	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
2024-08-30 10:27:03,533 [ 285935]   INFO - STDERR - 	... 12 more
```

**Comment by Blarc** [comment]
It's hard to tell what's wrong, because it seems the server you're sending your request to, does not respond with any error message. Do you maybe have access to the server and can you check the logs?
