### ISSUE TITLE
throw java.lang.NoClassDefFoundError when click generate button

### ISSUE THREAD

**Issue by wangtao94** [Blarc/ai-commits-intellij-plugin#300]
Unhandled exception in [ComponentManager(ApplicationImpl@664874782), com.intellij.codeWithMe.ClientIdContextElementPrecursor@74725a30, CoroutineName(com.github.blarc.ai.commits.intellij.plugin.settings.clients.openAi.OpenAiClientService), ModalityState.NON_MODAL, Dispatchers.Default]

java.lang.NoClassDefFoundError: retrofit2/converter/jackson/JacksonConverterFactory
	at dev.ai4j.openai4j.OpenAiClient.builder(OpenAiClient.java:122)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel.<init>(OpenAiStreamingChatModel.java:106)
	at dev.langchain4j.model.openai.OpenAiStreamingChatModel$OpenAiStreamingChatModelBuilder.build(OpenAiStreamingChatModel.java:465)
	at com.github.blarc.ai.commits.intellij.plugin.settings.clients.openAi.OpenAiClientService.buildStreamingChatModel(OpenAiClientService.kt:73)
	at com.github.blarc.ai.commits.intellij.plugin.settings.clients.openAi.OpenAiClientService$buildStreamingChatModel$1.invokeSuspend(OpenAiClientService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ApplicationImpl@664874782), com.intellij.codeWithMe.ClientIdContextElementPrecursor@74725a30, CoroutineName(com.github.blarc.ai.commits.intellij.plugin.settings.clients.openAi.OpenAiClientService), ModalityState.NON_MODAL, StandaloneCoroutine{Cancelled}@3844b89f, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: retrofit2.converter.jackson.JacksonConverterFactory PluginClassLoader(plugin=PluginDescriptor(name=AI Commits, id=com.github.blarc.ai-commits-intellij-plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.3\plugins\AICommits, version=2.9.0, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Git, id=Git4Idea, moduleName=intellij.vcs.git/terminal, descriptorPath=intellij.vcs.git.terminal.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\plugins\vcs-git, version=243.22562.145, package=git4idea.terminal, isBundled=true), PluginDescriptor(name=Git, id=Git4Idea, moduleName=intellij.vcs.git/newUiOnboarding, descriptorPath=intellij.vcs.git.newUiOnboarding.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\plugins\vcs-git, version=243.22562.145, package=git4idea.newUiOnboarding, isBundled=true), PluginDescriptor(name=Git, id=Git4Idea, moduleName=intellij.vcs.git.coverage, descriptorPath=intellij.vcs.git.coverage.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\plugins\vcs-git, version=243.22562.145, package=com.intellij.vcs.git.coverage, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=Git, id=Git4Idea, descriptorPath=plugin.xml, path=C:\0-tacrux\0-software\0-installed\JetBrains\Toolbox\IntelliJ IDEA Ultimate\plugins\vcs-git, version=243.22562.145, package=git4idea, isBundled=true), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 11 more

**Comment by Blarc** [comment]
Hey @wangtao94,

sorry for late response. This seems like an isolated class-loading issue. Could you please try these quick steps to resolve it:
1. **Invalidate IDE Caches:** `File → Invalidate Caches → Invalidate and Restart`.
2. **Reinstall Plugin:** Uninstall _AI Commits_, restart IDE, then reinstall.
3. **Check for Conflicts:** Temporarily disable other plugins and see if the issue persists.

If it still occurs, let me know your IDE version and share logs (`Help → Show Log in Files`). Thanks!
